export const Data = [
    {
        name: "Adam's Peak",
        type: "Religious",
        description: "Adam’s Peak is a breathtaking and spiritually significant mountain in central Sri Lanka, rising about 2,243 m above sea level with stunning panoramic views. Renowned for the sacred rock formation near its summit called Sri Pada (“sacred footprint”), the peak draws thousands of pilgrims and visitors each year during the climbing season from December to May. Buddhists believe the footprint is that of the Buddha, Hindus see it as Lord Shiva’s, and many Christians and Muslims associate it with Adam’s first step on Earth—making it a revered site for people of diverse faiths. The climb, often undertaken at night to reach the top in time for sunrise, offers an unforgettable experience of nature, culture and spiritual heritage.",
        background: "/adamsPeak/adams-background.webp",
        count:"01/17",
        galleryImages: [
            "/adamsPeak/adams1.webp",
            "/adamsPeak/adams2.webp",
            "/adamsPeak/adams3.webp",
            "/adamsPeak/adams4.webp"
        ]
    },
    {
        name: "Anuradhapura",
        type: "Religious",
        description: "Anuradhapura, in Sri Lanka’s North Central Province, is an ancient sacred city and UNESCO World Heritage Site. It was the island’s first major capital, flourishing from the 5th century BCE for over 1,000 years, and remains one of Asia’s oldest continuously inhabited cities. The city features well‑preserved ruins, including stupas, temples, palaces, and irrigation systems. A highlight is the Jaya Sri Maha Bodhi, a sacred fig tree over 2,300 years old from the original Bodhi tree under which the Buddha attained enlightenment. Today, it is a major pilgrimage site and a destination for travellers seeking history, culture, and spiritual heritage.",
        background: "/anuradhapura/pure-background.webp",
        count:"02/17",
        galleryImages: [
            "/anuradhapura/pure1.webp",
            "/anuradhapura/pure2.webp",
            "/anuradhapura/pure3.webp",
            "/anuradhapura/pure4.webp",
            "/anuradhapura/pure5.webp",
            "/anuradhapura/pure6.webp",
            "/anuradhapura/pure7.webp",
            "/anuradhapura/pure8.webp",
            "/anuradhapura/pure9.webp",
            "/anuradhapura/pure10.webp",
            "/anuradhapura/pure11.webp",
            "/anuradhapura/pure12.webp",
            "/anuradhapura/pure13.webp",
            "/anuradhapura/pure14.webp",
            "/anuradhapura/pure15.webp",
            "/anuradhapura/pure16.webp",
            "/anuradhapura/pure17.webp",
            "/anuradhapura/pure18.webp",
            "/anuradhapura/pure19.webp",
            "/anuradhapura/pure20.webp",
            "/anuradhapura/pure21.webp",
            "/anuradhapura/pure22.webp",
            "/anuradhapura/pure23.webp",
            "/anuradhapura/pure24.webp",
        ]
    },
    {
        name: "Arugam Bay",
        type: "Beach",
        description: "Arugam Bay is a famous coastal destination on Sri Lanka’s southeast coast, known for its beautiful sandy beach and world-class surfing. Once a quiet fishing village, it has become one of the country’s most popular spots for surf tourism, hosting international surf events and offering waves for all skill levels. The beach and surrounding area also attract visitors with its laid-back atmosphere, beachside cafés, and access to nearby natural attractions like lagoons and national parks.",
        background: "/arugamBay/arugam-background.webp",
        count:"03/17",
        galleryImages: [
            "/arugamBay/arugam1.webp",
            "/arugamBay/arugam2.webp",
            "/arugamBay/arugam3.webp",
            "/arugamBay/arugam4.webp",
            "/arugamBay/arugam5.webp",
            "/arugamBay/arugam6.webp",
            "/arugamBay/arugam7.webp",
            "/arugamBay/arugam8.webp",
            "/arugamBay/arugam9.webp",
            "/arugamBay/arugam10.webp",
            "/arugamBay/arugam11.webp"
        ]
    },
    {
        name: "Dambulla Cave Temple",
        type: "Religious",
        description: "The Dambulla Cave Temple, also known as the Golden Temple of Dambulla, is a remarkable ancient Buddhist site in central Sri Lanka. This UNESCO World Heritage Site features a complex of rock caves filled with hundreds of Buddha statues, vibrant murals, and sacred shrines carved into the cliffside. It has been a place of worship for over 2,000 years and offers visitors a fascinating glimpse into Sri Lanka’s rich religious and artistic heritage.",
        background: "/dabulla/dabulla-background.webp",
        count:"04/17",
        galleryImages: [
            "/dabulla/dabulla1.webp",
            "/dabulla/dabulla2.webp",
            "/dabulla/dabulla3.webp",
            "/dabulla/dabulla4.webp",
            "/dabulla/dabulla5.webp",
            "/dabulla/dabulla6.webp",
        ]
    },
    {
        name: "Temple of the Tooth",
        type: "Religious",
        description: "The Temple of the Tooth, or Sri Dalada Maligawa, is a sacred Buddhist temple in Kandy, Sri Lanka, that houses the relic of the tooth of the Buddha. It is one of the most important pilgrimage sites for Buddhists worldwide and a UNESCO World Heritage Site, known for its rich history, daily rituals, and the grand annual Kandy Esala Perahera festival.",
        background: "/dalada/dalada-background.webp",
        count:"05/17",
        galleryImages: [
            "/dalada/dalada1.webp",
            "/dalada/dalada2.webp",
            "/dalada/dalada3.webp",
            "/dalada/dalada4.webp",
            "/dalada/dalada5.webp",
            "/dalada/dalada6.webp",
            "/dalada/dalada7.webp",
        ]
    },
    {
        name: "Nuwara Eliya",
        type: "Nature",
        description: "Nuwara Eliya is a picturesque hill-country city in the Central Province of Sri Lanka, often called “Little England” because of its cool climate and colonial charm. Perched high in the mountains at about 1,868 m (6,128 ft) above sea level, it’s surrounded by rolling tea plantations, lush landscapes, and misty peaks — making it one of the country’s most scenic destinations. The area is known for its temperate weather, historic British-era architecture, and as a gateway to waterfalls, lakes like Gregory Lake, and nature attractions ideal for sightseeing and relaxation.",
        background: "/eliya/eliya-background.webp",
        count:"06/17",
        galleryImages: [
            "/eliya/eliya1.webp",
            "/eliya/eliya2.webp",
            "/eliya/eliya3.webp",
            "/eliya/eliya4.webp",
            "/eliya/eliya5.webp",
            "/eliya/eliya6.webp",
            "/eliya/eliya7.webp",
            "/eliya/eliya8.webp",
            "/eliya/eliya9.webp",
        ]
    },
    {
        name: "Ella",
        type: "Nature",
        description: "Ella is a charming hill-country town in Sri Lanka, famous for its cool climate, lush green landscapes, and breathtaking views. Surrounded by tea plantations, misty mountains, and waterfalls, Ella offers popular attractions such as Nine Arches Bridge, Little Adam’s Peak, Ella Rock, and Ravana Falls. Its relaxed atmosphere and natural beauty make Ella an ideal destination for nature lovers, hikers, and travelers seeking peace and adventure.",
        background: "/ella/ella-background.webp",
        count:"07/17",
        galleryImages: [
            "/ella/ella1.webp",
            "/ella/ella2.webp",
            "/ella/ella3.webp",
            "/ella/ella4.webp",
            "/ella/ella5.webp",
            "/ella/ella6.webp",
            "/ella/ella7.webp",
            "/ella/ella8.webp",
            "/ella/ella9.webp"
        ]
    },
    {
        name: "Galle Fort",
        type: "Historical",
        description: "Galle Fort is a historic coastal fortress in southern Sri Lanka, built by the Portuguese and later developed by the Dutch. A UNESCO World Heritage Site, it is known for its well-preserved colonial architecture, stone ramparts, lighthouse, and scenic ocean views, offering visitors a unique blend of history, culture, and charm.",
        background: "/fort/fort-background.webp",
        count:"08/17",
        galleryImages: [
            "/fort/fort1.webp",
            "/fort/fort2.webp",
            "/fort/fort3.webp",
            "/fort/fort4.webp",
            "/fort/fort5.webp",
            "/fort/fort6.webp",
            "/fort/fort7.webp",
            "/fort/fort8.webp",
            "/fort/fort9.webp",
            "/fort/fort10.webp",
            "/fort/fort11.webp",
        ]
    },
    {
        name: "Hikkaduwa Beach",
        type: "Beach",
        description: "Hikkaduwa Beach is a popular coastal destination on Sri Lanka’s southwest coast, known for its golden sands, coral reefs, and lively surf scene. The area offers excellent snorkeling and diving among colorful coral gardens and sea turtles, as well as waves suited for surfers of all levels. With vibrant beach bars, sunsets over the Indian Ocean, and lots of water activities, Hikkaduwa is a classic beach spot for visitors seeking both adventure and relaxation.",
        background: "/hikkaduwa/hikkaduwa-background.webp",
        count:"09/17",
        galleryImages: [
            "/hikkaduwa/hikkaduwa1.webp",
            "/hikkaduwa/hikkaduwa2.webp",
            "/hikkaduwa/hikkaduwa3.webp",
            "/hikkaduwa/hikkaduwa4.webp",
            "/hikkaduwa/hikkaduwa5.webp",
            "/hikkaduwa/hikkaduwa6.webp",
            "/hikkaduwa/hikkaduwa7.webp",
            "/hikkaduwa/hikkaduwa8.webp",
            "/hikkaduwa/hikkaduwa9.webp",
            "/hikkaduwa/hikkaduwa10.webp",
            "/hikkaduwa/hikkaduwa11.webp",
            "/hikkaduwa/hikkaduwa12.webp",
            "/hikkaduwa/hikkaduwa13.webp",
            "/hikkaduwa/hikkaduwa14.webp",
            "/hikkaduwa/hikkaduwa15.webp",
            "/hikkaduwa/hikkaduwa16.webp",
            "/hikkaduwa/hikkaduwa17.webp",
            "/hikkaduwa/hikkaduwa18.webp",
            "/hikkaduwa/hikkaduwa19.webp",
            "/hikkaduwa/hikkaduwa20.webp",
            "/hikkaduwa/hikkaduwa21.webp",
            "/hikkaduwa/hikkaduwa22.webp",
            "/hikkaduwa/hikkaduwa23.webp",
            "/hikkaduwa/hikkaduwa24.webp",
            "/hikkaduwa/hikkaduwa25.webp",
            "/hikkaduwa/hikkaduwa26.webp",
            "/hikkaduwa/hikkaduwa27.webp"
        ]
    },
    {
        name: "Lotus Tower",
        type: "Landmark",
        description: "Lotus Tower is an iconic 350‐metre landmark rising above Beira Lake in Colombo, Sri Lanka. Shaped like a blooming lotus flower—an important symbol of purity and cultural heritage—the tower is the tallest self‑supported structure in South Asia and offers breathtaking panoramic views of the city from its observation deck. Visitors can enjoy dining, exhibitions, events, and vibrant light displays that make it a must‑see attraction on the Colombo skyline.",
        background: "/lotus/lotus-background.webp",
        count:"10/17",
        galleryImages: [
            "/lotus/lotus1.webp",
            "/lotus/lotus2.webp",
            "/lotus/lotus3.webp",
        ]
    },
    {
        name: "Mihinthale",
        type: "Religious",
        description: "Mihintale is a sacred mountain peak near Anuradhapura in Sri Lanka, revered as the birthplace of Buddhism on the island. According to tradition, it was here in the 3rd century BC that the Buddhist monk Mahinda met King Devanampiyatissa, leading to the introduction of Buddhism in Sri Lanka—a landmark event in the country’s history. Today, Mihintale is a major pilgrimage and cultural destination, featuring ancient stairways, monasteries, stupas, meditation caves, and panoramic views that blend spiritual heritage with natural beauty.",
        background: "/mihintale/mihinthale-background.webp",
        count:"11/17",
        galleryImages: [
            "/mihintale/mihinthale1.webp",
            "/mihintale/mihinthale2.webp",
            "/mihintale/mihinthale3.webp",
            "/mihintale/mihinthale4.webp",
            "/mihintale/mihinthale5.webp",
            "/mihintale/mihinthale6.webp",
            "/mihintale/mihinthale7.webp",
            "/mihintale/mihinthale8.webp",
            "/mihintale/mihinthale9.webp",
            "/mihintale/mihinthale10.webp",
            "/mihintale/mihinthale11.webp"
        ]
    },
    {
        name: "Mirissa",
        type: "Beach",
        description: "Mirissa Beach is a beautiful crescent-shaped tropical beach on Sri Lanka’s south coast, in the Matara District, known for its golden sand, gentle waves, and relaxed seaside atmosphere. It’s a popular destination for swimming, sunbathing, and beginner-friendly surfing, as well as a hub for whale and dolphin watching during the peak season from November to April. Visitors can enjoy scenic spots like Parrot Rock and Coconut Tree Hill, beachfront cafés, seafood restaurants, and stunning sunsets over the Indian Ocean, making Mirissa a perfect mix of relaxation, adventure, and natural beauty.",
        background: "/mirissa/mirissa-background.webp",
        count:"12/17",
        galleryImages: [
            "/mirissa/mirissa1.webp",
            "/mirissa/mirissa2.webp",
            "/mirissa/mirissa3.webp",
            "/mirissa/mirissa4.webp",
            "/mirissa/mirissa5.webp",
            "/mirissa/mirissa6.webp",
            "/mirissa/mirissa7.webp",
            "/mirissa/mirissa8.webp",
            "/mirissa/mirissa9.webp",
            "/mirissa/mirissa10.webp",
            "/mirissa/mirissa11.webp",
            "/mirissa/mirissa12.webp"
        ]
    },
    {
        name: "Pinnawala Elephant Orphanage",
        type: "Nature",
        description: "Pinnawala Elephant Orphanage is a famous elephant care and conservation centre in Sri Lanka, established in 1975 to rescue and nurture orphaned and abandoned Asian elephants. Located in Pinnawala village near Kegalle, it is home to one of the largest captive elephant herds in the world, where visitors can observe daily routines such as feeding, bottle‑feeding of calves, and the unforgettable sight of elephants walking to and bathing in the nearby Maha Oya River. This unique experience offers a close‑up look at these gentle giants and is one of the island’s most memorable wildlife attractions.",
        background: "/pinnawala/pinnawala-background.webp",
        count:"13/17",
        galleryImages: [
            "/pinnawala/pinnawala1.webp",
            "/pinnawala/pinnawala2.webp",
            "/pinnawala/pinnawala3.webp",
            "/pinnawala/pinnawala4.webp"
        ]
    },
    {
        name: "Polonnaruwa",
        type: "Historical",
        description: "Polonnaruwa is one of Sri Lanka’s most remarkable ancient cities and a UNESCO World Heritage Site, celebrated for its well‑preserved archaeological ruins that showcase the island’s medieval golden age. Once the second capital of Sri Lanka (11th–13th centuries CE), the city flourished under powerful kings who built magnificent palaces, temples, stupas, and advanced irrigation systems like the vast Parakrama Samudra reservoir. Highlights include the stunning Gal Vihara rock‑carved Buddha statues and the sacred Quadrangle of monuments blending Buddhist and Hindu art and architecture. Today, Polonnaruwa offers travellers a fascinating journey through history amid serene landscapes and cultural wonders.",
        background: "/polonnaruwa/polonnaruwa-background.webp",
        count:"14/17",
        galleryImages: [
            "/polonnaruwa/polonnaruwa1.webp",
            "/polonnaruwa/polonnaruwa2.webp",
            "/polonnaruwa/polonnaruwa3.webp",
            "/polonnaruwa/polonnaruwa4.webp",
            "/polonnaruwa/polonnaruwa5.webp",
            "/polonnaruwa/polonnaruwa6.webp",
            "/polonnaruwa/polonnaruwa7.webp",
            "/polonnaruwa/polonnaruwa8.webp",
            "/polonnaruwa/polonnaruwa9.webp",
            "/polonnaruwa/polonnaruwa10.webp",
            "/polonnaruwa/polonnaruwa11.webp",
            "/polonnaruwa/polonnaruwa12.webp",
            "/polonnaruwa/polonnaruwa13.webp",
        ]
    },
    {
        name: "Sigiriya",
        type: "Historical",
        description: "Sigiriya, also known as Lion Rock, is an ancient rock fortress in central Sri Lanka and one of the country’s most iconic landmarks. Rising about 180 m above the surrounding plains, it was built in the 5th century by King Kashyapa as a royal palace and stronghold. Today, Sigiriya is a UNESCO World Heritage Site, famous for its remarkable engineering, ancient frescoes, landscaped gardens, and stunning views from the top.",
        background: "/sigiriya/sigiriya-background.webp",
        count:"15/17",
        galleryImages: [
            "/sigiriya/sigiriya1.webp",
            "/sigiriya/sigiriya2.webp",
            "/sigiriya/sigiriya3.webp",
            "/sigiriya/sigiriya4.webp",
            "/sigiriya/sigiriya5.webp",
            "/sigiriya/sigiriya6.webp",
            "/sigiriya/sigiriya7.webp",
            "/sigiriya/sigiriya8.webp",
            "/sigiriya/sigiriya9.webp",
            "/sigiriya/sigiriya10.webp",
            "/sigiriya/sigiriya11.webp"
        ]
    },
    {
        name: "Unawatuna",
        type: "Beach",
        description: "Unawatuna Beach, just a few kilometers from Galle, is one of Sri Lanka’s most famous coastal destinations. Known for its golden sands, turquoise waters, and vibrant coral reefs, it’s perfect for swimming, snorkeling, and beginner-friendly surfing. Despite its popularity, the area still shelters the rare purple-faced langur, offering a unique blend of wildlife and natural beauty for visitors to enjoy.",
        background: "/unawatuna/unawatuna-background.webp",
        count:"16/17",
        galleryImages: [
            "/unawatuna/unawatuna1.webp",
            "/unawatuna/unawatuna2.webp",
            "/unawatuna/unawatuna3.webp",
            "/unawatuna/unawatuna4.webp",
            "/unawatuna/unawatuna5.webp",
            "/unawatuna/unawatuna6.webp",
            "/unawatuna/unawatuna7.webp",
            "/unawatuna/unawatuna8.webp",
            "/unawatuna/unawatuna9.webp",
            "/unawatuna/unawatuna10.webp"
        ]
    },
    {
        name: "Yala National Park",
        type: "Nature",
        description: "Yala National Park, located in southeastern Sri Lanka, is one of the island’s most famous wildlife reserves and a top safari destination. It spans diverse landscapes—from grasslands and forests to lagoons and sandy beaches—and is home to an extraordinary variety of animals, including one of the highest leopard densities in the world, elephants, sloth bears, deer, crocodiles, and over 200 bird species. A safari here offers unforgettable opportunities to experience Sri Lanka’s rich biodiversity in its natural habitat.",
        background: "/yala/yala-background.webp",
        count:"17/17",
        galleryImages: [
            "/yala/yala1.webp",
            "/yala/yala2.webp",
            "/yala/yala3.webp",
            "/yala/yala4.webp",
            "/yala/yala5.webp",
            "/yala/yala6.webp",
            "/yala/yala7.webp",
            "/yala/yala8.webp",
            "/yala/yala9.webp",
            "/yala/yala10.webp",
            "/yala/yala11.webp",
            "/yala/yala12.webp",
            "/yala/yala13.webp",
            "/yala/yala14.webp",
            "/yala/yala15.webp",
            "/yala/yala16.webp",
            "/yala/yala17.webp",
            "/yala/yala18.webp",
            "/yala/yala19.webp",
            "/yala/yala20.webp"
        ]
    }
];
